### ISSUE TITLE
Banner is reversed in Overview tab

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#41]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->MakeWebBetter-->MWB Booking for WooCommerce-->Overview
Version: 2.0.0
Description:
Designing is not appropriate
![s23](https://user-images.githubusercontent.com/86114080/126037188-61450073-3e97-4fae-b6d3-145793f5acca.png)

**Comment by vivekkushwaha-cedcoss** [comment]
updated

**Comment by shrishti-mwb** [comment]
Done
