### ISSUE TITLE
Overview Doc is incomplete

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#42]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->MakeWebBetter-->MWB Booking for WooCommerce-->Overview
Version: 2.0.0
Description:
Designing is not appropriate.
![S24](https://user-images.githubusercontent.com/86114080/126037343-00570d07-1b0b-4601-8cc3-0b7ee8862886.png)

**Comment by vivekkushwaha-cedcoss** [comment]
updated

**Comment by shrishti-mwb** [comment]
Done
