### ISSUE TITLE
Onboarding pop up is very big in tablet

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#43]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->MakeWebBetter-->MWB Booking for WooCommerce-->General settings
Version: 2.0.0
Description:
Designing is not appropriate in responsive testing
![s27](https://user-images.githubusercontent.com/86114080/126037748-fc1ed458-5073-495d-b630-3d60ae895e8a.png)

**Comment by husainrizvit** [comment]
updated

**Comment by shrishti-mwb** [comment]
Done
