### ISSUE TITLE
Booked dates are not visible in calendar 

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#44]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->MakeWebBetter-->MWB Booking for WooCommerce-->Booking Calendar
Version: 2.0.0
Description:
Booked dates are not visible in Booking calendar.
![s29](https://user-images.githubusercontent.com/86114080/126123136-ba105b56-f9dd-4cc5-82e6-47ec1cc7ef5d.png)
![s30](https://user-images.githubusercontent.com/86114080/126123143-9bd00940-4da5-4943-9e5f-f9fff665b977.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
