### ISSUE TITLE
Booked dates are not shown in WooCommerce order tab

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#45]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->WooCommerce -->Orders-->Click on any booking order-->Booked dates are not shown
Version: 2.0.0
Description:
Booked dates are not shown in the order section in woocommerce.
![s29](https://user-images.githubusercontent.com/86114080/126127153-1dd76ca6-f9ac-4c40-a094-95efedff5ef9.png)
![s31](https://user-images.githubusercontent.com/86114080/126127565-feee700a-8d34-48c8-9f26-d1f6eb4718a0.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
