### ISSUE TITLE
Accepting people count in negative numeric number

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#47]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Go to store-->Add any MWB Booking products-->Decrease count of people-->Proceed
Version: 2.0.0
Description:
Accepting people count in negative numeric number 
![s36](https://user-images.githubusercontent.com/86114080/126133139-0e03f5ec-a3da-45b8-aa64-07faea1f0aa0.png)
and successfully placing order without alert.

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Settings are updated from backend but not changing in frontend.
![s79](https://user-images.githubusercontent.com/86114080/127434590-680454fe-dec8-4725-bb08-b8e24202425a.png)
![s82](https://user-images.githubusercontent.com/86114080/127434984-8aea5121-3a90-44dd-9a7e-9a439d6b575f.png)

**Comment by vivekkushwaha-cedcoss** [comment]
updated

**Comment by shrishti-mwb** [comment]
Done
