### ISSUE TITLE
Issue in date selection

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#48]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Go to store-->Add any MWB Booking products-->Select dates.
Version: 2.0.0
Description:
Allows greater 'From date' and lesser 'To date'
![s37](https://user-images.githubusercontent.com/86114080/126135145-dc017e92-0fad-4b5f-8eeb-53012e6a79cd.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
