### ISSUE TITLE
Issue in total cost

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#50]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Go to store-->MWB booking products-->Any product-->select dates-->people count=0
Version: 2.0.0
Description:
Total cost is 0 when people count is zero.
![s40](https://user-images.githubusercontent.com/86114080/126263940-d9c8ff38-029e-4406-93ab-57c10c634a88.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
