### ISSUE TITLE
Nothing difference in 'booking confirmation' and normal orders

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#51]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->Products-->edit product-->check booking confirmation-->update
Go to store-->Select any product-->Add to cart-->Checkout-->order placed
Version: 2.0.0
Description:
There is no difference between 'booking  confirmation' tab and normal tab. Both are in processing status. There is no any tab to confirm order.
![s41](https://user-images.githubusercontent.com/86114080/126267539-71365816-50da-4b18-8ac2-f339c1827f37.png)
![s43](https://user-images.githubusercontent.com/86114080/126267548-2b4a9b25-ff61-4e56-8b8b-f12ebda0e3e1.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
