### ISSUE TITLE
No option available to cancel order after booking

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#52]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->products-->edit product-->check cancellation allowed-->update
Go to store-->add to cart the edited product-->checkout-->order placed
Version: 2.0.0
Description:
There is no option available for users to cancel order after placing of the product which has cancellation allowed.
![s42](https://user-images.githubusercontent.com/86114080/126268970-c5fc4bbe-590a-47e3-a92d-8c9727712a25.png)
![s44](https://user-images.githubusercontent.com/86114080/126269127-fb16fce6-7825-42a3-8310-74dad70753c8.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
