### ISSUE TITLE
Issue in service cost 

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#53]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->Product->Edit product->Services-->Add extra services(uncheck)-->Booking services-->add service
Go to store-->Go to the MWB booking Product-->Go to the edited product(unchecked services)
Version: 2.0.0
Description: Extra services are disabled and added in booking service and still visible on store-end
![s45](https://user-images.githubusercontent.com/86114080/126274176-e00088b3-981e-42dd-882a-74b2367c0cea.png)
![s46](https://user-images.githubusercontent.com/86114080/126274202-a3a03ee0-1f29-4188-8164-13ab8411360c.png)
![s47](https://user-images.githubusercontent.com/86114080/126274204-4ed51f86-c9d8-4944-9e8d-b6ebb8acc5ce.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
