### ISSUE TITLE
Issue in availability

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#54]
WordPress Version: 5.7.2
WooCommerce version: 5.5.1
Area Path: Admin panel-->Products-->Add products-->Availability-->Maximum booking per user(1)
Go to store-->Add to cart that product twice-->Place order
Version: 2.0.0
Description:
We set the maximum booking per user 1 but we can buy 2 units of that product
![s49](https://user-images.githubusercontent.com/86114080/126278131-eb85b223-d762-4b60-885a-db1641d3158e.png)
![s48](https://user-images.githubusercontent.com/86114080/126278123-d312e8eb-f6d4-4427-84d2-0780d02b611e.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
