### ISSUE TITLE
Issue in time selection

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#55]
WordPress Version: 5.8
WooCommerce version: 5.5.2
Area Path: Go to store-->Add any MWB Booking products-->Select dates-->Select time
Version: 2.0.0
Description:
Allows greater 'From Time' and lesser 'To Time'
![s81](https://user-images.githubusercontent.com/86114080/127435415-942ac19e-abe5-48b3-bff6-8ab62ad3151b.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
