### ISSUE TITLE
Issue in Date Selection

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#56]
WordPress Version: 5.8
WooCommerce version: 5.5.2
Area Path: Go to store-->Add any MWB Booking products-->Select dates.
Version: 2.0.0
Description:
Giving alert when selecting dates.
![s80](https://user-images.githubusercontent.com/86114080/127435694-fb816481-b050-48d5-9150-99cb0f2f955e.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by shrishti-mwb** [comment]
Done
