### ISSUE TITLE
QA Issues

### ISSUE THREAD

**Issue by shrishti-mwb** [Makewebbetter/mwb-bookings-for-woocommerce#60]
**### QA Issue on MWB Booking for WooCommerce Plugin**

**Wordpress version is not updated in main file**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\mwb-bookings-for-woocommerce.php(line25)

**Woocommerce Tested upto version is not mentioned in main file**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\mwb-bookings-for-woocommerce.php

**Description is not properly written in main file**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\mwb-bookings-for-woocommerce.php(line17)

**Multiline comment in single line**
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\admin\css\mwb-admin.css(line 321)

**Empty folder**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\admin\css\mwb-bookings-for-woocommerce-admin-global.css

**Empty php tag open**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\admin\partials\mwb-bookings-for-woocommerce-booking-calendar-listing.php(line23)

**Used Inline CSS**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\admin\partials\mwb-bookings-for-woocommerce-template.php(line31)

**Used file_get_contents**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\includes\class-mwb-bookings-for-woocommerce.php(line 561)

**Used Curl**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\includes\class-mwb-bookings-for-woocommerce-onboarding-steps.php(line 731,735,740)

 **Used Console**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\datatables.net\js\jquery.dataTables.min.js(line 75)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\example\amd\main.js(line 134, line 136)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\example\browserify\main.js(line 129,131)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\website\website.js(line 135, line 153)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\moment.min.js(line1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\full-calendar\main.js(line65,2919,3153,3284,3315,5080,5081,6500,7277)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\full-calendar\main.min.js(line 6)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\material-design\material-components-v5.0-web.min.js(line 1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\material-design\material-components-web.min.js(line 1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\moment-js\moment.min.js(line 1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\select-2\mwb-bookings-for-woocommerce-select2.js(line1,line2)

 **Used .Click**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\datatables.net-responsive\js\dataTables.responsive.min.js(line 16, line 26)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\example\amd\main.js(line 20, line 21)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\example\browserify\main.js(line15,16)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\website\website.js(line 11,line 12)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\material-design\material-components-v5.0-web.min.js(line 1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\full-calendar\main.js(line 6344,6345)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\full-calendar\main.min.js(line6)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\material-design\material-components-web.min.js(line1)
C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\material-design\material-lite.min.js(line8)

 **Empty folder**

C:\Users\asus\Desktop\Shrishti\mwb-bookings-for-woocommerce\package\lib\daterangepicker-master\example\browserify\bundle.js

https://docs.google.com/document/d/14l6YQ4uxLz-H6tbYQjgKcm_pYA-bkgWiqI15FRCETL0/edit?usp=sharing

**Comment by vivekkushwaha-cedcoss** [comment]
Fixable issues are fixed. few are library issues which can not be fixed,
Please check the doc for detailed comment on every issue.
https://docs.google.com/document/d/14l6YQ4uxLz-H6tbYQjgKcm_pYA-bkgWiqI15FRCETL0/edit?usp=sharing

**Comment by shrishti-mwb** [comment]
Done
