### ISSUE TITLE
Overview page placement issue.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/mwb-bookings-for-woocommerce#61]
**Bug Name -** Overview page placement issue.
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**Plugin Version -** 2.0.0
**Description -**

![image](https://user-images.githubusercontent.com/76723393/128868776-0c81bb6a-f79f-4d40-b198-c76428490829.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed
