### ISSUE TITLE
Remove Developer Setting Tab.

### ISSUE THREAD

**Issue by AnuraktSachan-CEDCOSS** [Makewebbetter/mwb-bookings-for-woocommerce#62]
**Bug Name -** Remove Developer Setting Tab. 
**Area Path -** 
**Status -** New
**Woo Commerce Version -** 5.5.2
**WordPress Version -** 5.8
**Plugin Version -** 2.0.0
**Description -**
![image](https://user-images.githubusercontent.com/76723393/128868949-2093b981-4d41-4918-8c5e-5caeacbfba57.png)

**Comment by vivekkushwaha-cedcoss** [comment]
need confirmation will update soon

**Comment by AnuraktSachan-CEDCOSS** [comment]
as per developer, its required.
