### ISSUE TITLE
Text-domain Issues 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-bookings-for-woocommerce#64]
WP: 5.8
WC: 5.6
Plugin: Mwb Bookings For WooCommerce
Version : 2.0.1
Description: There are two strings with different text-domain
Text-domain: mwb-booking-for-woocommerce
admin/class-mwb-bookings-for-woocommerce-admin.php ( 561, 567 )
![image](https://user-images.githubusercontent.com/85384857/132689550-087f52e5-0b52-41bb-83a6-a78a837e0a2d.png)

**Comment by vivekkushwaha-cedcoss** [comment]
updated

**Comment by Sukirti-CEDCOSS** [comment]
Verified
