### ISSUE TITLE
Issue with multi-site compatibility test

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-bookings-for-woocommerce#65]
WP: 5.8
WC: 5.6
Plugin:  Bookings For WooCommerce PRO
Version : 1.0.1
Description: The licensing feature  seems not to be working fine as we create a new site 
![image](https://user-images.githubusercontent.com/85384857/132696731-e7de9688-fb58-4c07-837f-81b15c4d572c.png)

**Comment by vivekkushwaha-cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
Verified
