### ISSUE TITLE
The plugin is not reflecting update notice

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/mwb-bookings-for-woocommerce#67]
WooCommerce: 6.1.1
Word Press: 5.8.3
Description:
The plugin is not reflecting update notice
![image](https://user-images.githubusercontent.com/85384857/150631714-fea60daa-7a25-44b5-9cde-fefcc33ec0eb.png)

**Comment by Stuti-Cedcoss** [comment]
fixed

**Comment by Sukirti-CEDCOSS** [comment]
verified
